LOCAL_MQTT_BROKER_ADDRESS = "localhost"
LOCAL_MQTT_BROKER_PORT = 1883
LOCAL_MQTT_USER_NAME = None

GW_MQTT_BROKER_ADDRESS = "localhost"
GW_MQTT_BROKER_PORT = 18831
GW_MQTT_USER_NAME = None

WORLD_ROOT_ALIAS = "dwtest"

LOCAL_MQTT_MESSAGE_DELTA_S = 0.4
GW_MQTT_MESSAGE_DELTA = 0.4

SCADA_REPORTING_PERIOD_S = 300
