LOCAL_MQTT_BROKER_ADDRESS = 'broker.hivemq.com'
LOCAL_MQTT_USER_NAME = None

GW_MQTT_BROKER_ADDRESS = 'mqtt.eclipseprojects.io'
GW_MQTT_USER_NAME = None

ATN_G_NODE_ALIAS = 'dw1.isone.nh.orange.1'

LOCAL_MQTT_MESSAGE_DELTA_S = 0.4
GW_MQTT_MESSAGE_DELTA = 0.4

SCADA_REPORTING_PERIOD_S = 300