# MQTT related
LOCAL_MQTT_BROKER_ADDRESS = "localhost"
LOCAL_MQTT_BROKER_PORT = 1883
LOCAL_MQTT_USER_NAME = None

GW_MQTT_BROKER_ADDRESS = "mqtt.eclipseprojects.io"
GW_MQTT_BROKER_PORT = 1883
GW_MQTT_USER_NAME = None

WORLD_ROOT_ALIAS = "dwtest"

SCADA_REPORTING_PERIOD_S = 300
